### ISSUE TITLE
Names for GTDB species not in Keport

### ISSUE THREAD

**Issue by KristofferSandas** [FOI-Bioinformatics/nanometa_live#12]
The species names for the pathogen section are taken from the kreport, and therefore if a species is not in there, the name will not be found. For now I made it so that the list says "not found in DB" if the species is not in the kreport.  To find the name from a config file ID, the kraken DB file would have to be used. 

We'll see what the solution could be once we get to the automatic BLAST DB build etc.

**Comment by druvus** [comment]
We now handle missing taxids by checking the updated config file.
